name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history so branches are available

    - name: Fetch all branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Khlick"
        git config --global user.email "khrisgriffis@gmail.com"
        git worktree add ../site origin/site
        rsync -a --delete src/ ../site/
        git -C ../site add --all  # Use the -C option to specify the worktree directory
        git -C ../site commit -m "Deploy to GitHub Pages"
        git -C ../site push origin site
